import React from "react";

export const metadata = {
  title: "About Page",
  description: "Generated by create next app",
};

const page = () => {
  return <div className="text-3xl font-bold underline">page</div>;
};

export default page;
